/* This file is generated, do not edit! */
package pandas.tseries.tests.test_resample;
typedef DataError = pandas.core.groupby.DataError;